### ISSUE TITLE
Services fail with OTT2.9draft12 but not with OTT2.8

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#104]
e.g.

    curl https://devapi.opentreeoflife.org/taxomachine/v1/autocompleteQuery \
      -H 'Content-Type: application/json' \
      -H 'Accept: application/json, text/javascript, */*; q=0.01' \
      --data-binary '{"queryString":"bacteria","contextName":"All life"}'

yields

     [ ]

**Comment by kcranston** [comment]
The build + indexing doesn't give any errors, so it is hard to tell what might be wrong.

**Comment by jar398** [comment]
@josephwb said he could not reproduce this, and JAR wonders if maybe the setup commands weren't all run.  PR #116 is related because it adds a command to do the whole initialization in a single step, making it much harder to make mistakes.  New db is running on devapi; we need to decide whether/when to move to production.

**Comment by jar398** [comment]
Not sure what this was about, but it seems fine now.
