### ISSUE TITLE
'unclassified' should be treated same as incertae sedis

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#108]
See https://github.com/OpenTreeOfLife/feedback/issues/147

OTTFlag.java has
	UNCLASSIFIED ("unclassified", false),
(and similarly for affiliated flags).  That should be 'true', not 'false'.

**Comment by hyanwong** [comment]
Would be v. useful to me to get this fix in, given it seems a trivial one. Any ETA for this?

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/taxomachine/pull/110
We had trouble building the taxomachine database recently, but when Joseph did it it worked. I'll see if he's willing to help out again.

**Comment by hyanwong** [comment]
Great, thanks. Sorry to bug about it.

**Comment by josephwb** [comment]
I am doing so right now. Should be available later tonight (I'll post when it is deployed).

**Comment by jar398** [comment]
@hyanwong sorry, we are experiencing technical difficulties, and it's not done yet.  hang on.

**Comment by josephwb** [comment]
Things are deployed on dev, but there is a concern that the DB is smaller than before, so things may be broke.

**Comment by jar398** [comment]
Deployed to production.
