### ISSUE TITLE
Add one or more context tests

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#111]
e.g.
curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names": ["Hylobates"], "context_name": "Mammals"}'
should yield Hylobates.  

(currently doesn't on dev, see https://github.com/OpenTreeOfLife/feedback/issues/147 )

**Comment by pmidford** [comment]
curl -X POST http:/devapi.opentreeoflife.org/v2/tnrs/infer_context -H "content-type:application/json" -d '{"names": ["Pan","Homo","Mus","Bufo"]}'
is also currently broken:
{
  "context_name" : "All life",
  "context_ott_id" : 805080,
  "ambiguous_names" : [ ]
}
instead of:
{
  "context_name" : "Tetrapods",
  "context_ott_id" : 229562,
  "ambiguous_names" : [ ]
}

**Comment by hyanwong** [comment]
Yes, it's not just Hylobates or primates. Over 6 thousand Passerines are broken too (do not appear under context:Vertebrates. From the top of my list (can provide the full list if need be)

'Abroscopus albogularis',
'Abroscopus schisticeps',
'Abroscopus superciliaris',
'Acanthagenys rufogularis',
'Acanthidops bairdii',
'Acanthisitta chloris',
'Acanthisittidae',
'Acanthiza apicalis',
'Acanthiza chrysorrhoa',
'Acanthiza ewingii',
'Acanthiza inornata',
'Acanthiza iredalei',
'Acanthiza katherina',
'Acanthiza lineata',
'Acanthiza murina',
'Acanthiza nana',
'Acanthiza pusilla',
'Acanthiza reguloides',
'Acanthiza robustirostris',
'Acanthiza uropygialis',
'Acanthizidae',
'Acanthorhynchus superciliosus',
'Acanthorhynchus tenuirostris',
'Acanthornis magna',
'Achaetops pycnopygius',
'Acridotheres albocinctus',
'Acridotheres cinereus',
....
'Zosterops stalkeri',
'Zosterops stresemanni',
'Zosterops tenuirostris',
'Zosterops vaughani',
'Zosterops vellalavella',
'Zosterops wallacei',
'Zosterops xanthochroa',

**Comment by hyanwong** [comment]
Works for  http://api.opentreeoflife.org/v2/tnrs/match_names, with OTT 2.9d12. So it's something to do with the dev servers

**Comment by jar398** [comment]
Right, the production server got an earlier, better working version of the taxomachine database. It doesn't have some of the TNRS taxon visibility changes we wanted, however. This is definitely still work in progress.

**Comment by hyanwong** [comment]
Oh yes, I see. It api.opentreeoflife still has this problem: https://github.com/OpenTreeOfLife/feedback/issues/147 . Damn. Was hoping that was fixed. Is this an easy one?

**Comment by jar398** [comment]
No, this is not an easy one. This is the Big Mysterious Taxomachine Bug
#104, that I just mentioned in a different thread, which has yet to be
solved. I think Joseph and/or Karen are working on this.

**Comment by hyanwong** [comment]
OK, thanks for the pointer. I'll just have to wait then.

**Comment by jar398** [comment]
#104 is done. time to review.
