### ISSUE TITLE
Taxonomy indexing is failing on devtree

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#115]
Issue initially reported here https://github.com/OpenTreeOfLife/feedback/issues/147, but I'm repeating it in the taxomachine repo because this is the appropriate place for it and it's critical and high priority.

The symptoms are (a) the database dump is much smaller than the previous one (b) contexts don't work.

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/taxomachine/issues/108  depends on this.  https://github.com/OpenTreeOfLife/taxomachine/issues/111 is also hard to close with its tests failing, and the tests depend on this.

**Comment by josephwb** [comment]
[This PR](https://github.com/OpenTreeOfLife/taxomachine/pull/116) should prevent this from ever happening again.
