### ISSUE TITLE
Non-bird offered as homonym even when context set to birds

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#120]
With the OTU 'Regulus' two homonyms are offered, and one of them (Thalassocaris) is a crustacean, not a bird. This is true even if the taxonomic context is set to birds.  (study pg_2015)

The 'unique name' does not help here since Thalassocaris is not a homonym, only its synonym Regulus is. 

This sort of defeats the main purpose of having contexts in the first place.

Obviously this is not just about the one example; offering out-of-context options is going to be a widespread source of frustration and error for curators.

**Comment by mtholder** [comment]
https://tree.opentreeoflife.org/curator/study/edit/pg_2015?tab=otu-mapping is the link.
It looks to me like a stale cache of the context name somewhere. If I load the study, I see "Birds" in that menu and get the 2 hits that @jar398 reports. But then if I change it to different context, and then back to "Birds" the search just reports the hit in birds.

**Comment by jimallman** [comment]
Thanks for the heads-up! It seems the initial mapping request is being submitted with the wrong context ("All life"), despite the UI clearly showing "Birds". Looking into this now...

**Comment by jimallman** [comment]
> It seems the initial mapping request is being submitted with the wrong context ("All life"), despite the UI clearly showing "Birds".

This has been happening during the first curation session for a study, before it's been saved in the curation app. When a study loads, we infer its search context by sampling taxa, but the updated UI (in this case, the selected "Birds") was not being captured in the Nexson. This is fixed now and working on **devtree**; see for example [study Foltz D., 2006](https://devtree.opentreeoflife.org/curator/study/edit/pg_1792/?tab=otu-mapping) (but please don't save this!).
