### ISSUE TITLE
Taxomachine needs to provide a MRCA method

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#121]
Finding MRCAs in the taxonomy is a service currently provided by treemachine. We could replicate this in tm-lite, but really it's more appropriate for taxonomy MRCA service to be provided by taxomachine.

See https://opentree.slack.com/archives/general/p1449680939000065

**Comment by josephwb** [comment]
Seems covered by [`lica`] (https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#lica).

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#lica
