### ISSUE TITLE
is_dubious vs. is_suppressed vs. is_not_otu vs. ... ?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#132]
An analysis of the v2 'is_dubious' flag is needed in order to give it an appropriate name in v3. I changed it to 'is_suppressed' for the spec but I don't think it's right, or if it's right then it's right in a sense that I don't know. (Suppressed from what? Why?)

This issue constitutes a reminder to myself to read the code to figure this out, and a notice to others that the spec may have to change, if what I figure out is that it should not be called 'is_suppressed'.

**Comment by jar398** [comment]
Here are the flags that lead to a taxon being 'suppressed':

	NOT_OTU ("not_otu", false),
	ENVIRONMENTAL ("environmental", false),
	ENVIRONMENTAL_INHERITED ("environmental_inherited", false),
	VIRAL ("viral", false),
	HIDDEN ("hidden", false),
	HIDDEN_INHERITED ("hidden_inherited", false),
	WAS_CONTAINER ("was_container", false),

This looks OK to me.

The suppression is suppression from TNRS consideration, and is unrelated to flag-based suppression from consideration in synthesis. Also the suppressed taxa are still visible via taxon_info. As long as the user-facing documentation makes this clear, I think things are OK the way they are in the spec right now (tnrs and taxonomy methods returning an `is_suppressed` flag). So I'll close the issue with no action.

**Comment by kcranston** [comment]
Is the list of flags for `is_suppressed` documented anywhere other than this issue? Including the list of flags in the API docs seems messy.

I am writing API docs, and the taxonomy docs define this as "taxa not included in TNRS results" and the TNRS docs define this as "taxa not accepted by OTT". I'd like to clarify, but want the docs to be accurate.

**Comment by jar398** [comment]
I put the lists [here](
https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/Taxon-flags#flags-leading-to-taxa-being-unavailable-for-tnrs),
so you can refer to that page.

**Comment by kcranston** [comment]
thanks!
