### ISSUE TITLE
nosetests: command not found

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/taxomachine#79]
On taxomachine master branch, up to date:
(venv)bash-3.2$ cd taxomachine
(venv)bash-3.2$ export TAXOMACHINE_SERVER=devapi.opentreeoflife.org/taxomachine
(venv)bash-3.2$ ./test.sh 
./test.sh:8: nosetests: command not found
(venv)bash-3.2$

**Comment by pmidford** [comment]
The updated test scripts seem to work (both when they pass and when there are problems).  Time to close this?
