### ISSUE TITLE
rank field in matches does not appear to be filled in

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/taxomachine#83]
maybe it is just wrong for some queries.

    curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/tnrs/match_names --data '{"do_approximate_matching": false, "names": ["Homo sapiens"]}'

produces: 

    {
      "governing_code" : "ICZN",
      "unambiguous_name_ids" : [ "Homo sapiens" ],
      "unmatched_name_ids" : [ ],
      "matched_name_ids" : [ "Homo sapiens" ],
      "context" : "Mammals",
      "includes_deprecated_taxa" : false,
      "includes_dubious_names" : false,
      "includes_approximate_matches" : false,
      "taxonomy" : {
        "author" : "open tree of life project",
        "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
        "source" : "ott2.8"
      },
      "results" : [ {
        "id" : "Homo sapiens",
        "matches" : [ {
          "is_deprecated" : false,
          "is_synonym" : false,
          "flags" : [ ],
          "search_string" : "homo sapiens",
          "score" : 1.0,
          "synonyms" : [ "Homo palestinus", "Homo melaninus", "Homo spelaeus", "Homo scythicus", "Homo proto-aethiopicus", "Homo monstrosus", "Homo dawsoni", "Homo cafer", "Homo eurafricanus", "Homo helmei", "man", "Homo sinicus", "Homo sapiens", "Homo cro-magnonensis", "Homo grimaldii", "Homo indicus", "Homo arabicus", "Homo patagonus", "Homo aurignacensis", "Homo drennani", "Homo troglodytes", "Homo australasicus", "Homo japeticus", "Homo grimaldiensis", "Homo hottentotus", "Homo neptunianus", "Homo hyperboreus", "Homo americanus", "human", "Homo capensis", "Homo kanamensis", "Homo columbicus", "Homo aethiopicus" ],
          "is_approximate_match" : false,
          "ot:ottId" : 770315,
          "matched_node_id" : 3553897,
          "rank" : "",
          "matched_name" : "Homo sapiens",
          "unique_name" : "Homo sapiens",
          "is_dubious" : false,
          "nomenclature_code" : "ICZN",
          "ot:ottTaxonName" : "Homo sapiens"
        } ]
      } ]
    }

note the empty rank string and the fact that rank is specified as species in OTT 2.8

**Comment by jar398** [comment]
See 64a93be3515837e79d55b0d87d8bbd99a26d0086 on v3 branch

**Comment by jar398** [comment]
The v3 API is showing `"rank" : "species"` for this call. No idea what the problem is/was but I'm sure you'll report it if you see it again.
