### ISSUE TITLE
might want to rename `matched_node_id` in match_names response to `node_id`

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/taxomachine#86]
that would improve the correspondence between the "taxon" and "match_names" services (and it is obvious that the OTU info is about the match, so the matched_ prefix is not that helpful).

**Comment by jar398** [comment]
If there's general agreement with #94 we can close this issue in favor of it.  I.e. never even return the node ids at all.

**Comment by jar398** [comment]
Alll the taxomachine node_ids are gone in the v3 API.
