### ISSUE TITLE
Internal server error in taxonomy/subtree webservice if OTT ID is invalid

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/taxomachine#91]
I accidentally typed an OTT ID incorrectly:

    curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" http://devapi.opentreeoflife.org/v2/taxonomy/subtree --data '{"ott_id": 328201}'

and got:

    {
      "exception" : "NullPointerException",
      "fullname" : "java.lang.NullPointerException",
      "stacktrace" : [ "org.opentree.taxonomy.plugins.taxonomy.subtree(taxonomy.java:103)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
    }

**Comment by jar398** [comment]
This seems to be fixed in the v3 API.  You still get an error, but it is a 400 and the message is sensible.
