### ISSUE TITLE
OTT ID returned more than once in a TNRS call

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/taxomachine#92]
Perhaps this is a feature, but it surprised me. It is by no means urgent, but if I run:

    curl -X POST -H "Content-Type":"application/json" -H"Accept":"application/json" http://api.opentreeoflife.org/v2/tnrs/match_names --data '{"do_approximate_matching": false, "names": ["Archaea"]}'

I get the following output, which contains OTT ID 996421 twice (first and third response).

    {
      "governing_code" : "undefined",
      "unambiguous_name_ids" : [ "Archaea" ],
      "unmatched_name_ids" : [ ],
      "matched_name_ids" : [ "Archaea" ],
      "context" : "All life",
      "includes_deprecated_taxa" : false,
      "includes_dubious_names" : false,
      "includes_approximate_matches" : false,
      "taxonomy" : {
        "author" : "open tree of life project",
        "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
        "source" : "ott2.8"
      },
      "results" : [ {
        "id" : "Archaea",
        "matches" : [ {
          "is_deprecated" : false,
          "is_synonym" : false,
          "flags" : [ ],
          "search_string" : "archaea",
          "score" : 1.0,
          "synonyms" : [ "Archaea", "archaea", "Archaebacteria", "Mendosicutes", "Metabacteria" ],
          "is_approximate_match" : false,
          "ot:ottId" : 996421,
          "matched_node_id" : 478643,
          "rank" : "",
          "matched_name" : "Archaea",
          "unique_name" : "Archaea (domain in cellular organisms)",
          "is_dubious" : false,
          "nomenclature_code" : null,
          "ot:ottTaxonName" : "Archaea"
        }, {
          "is_deprecated" : false,
          "is_synonym" : false,
          "flags" : [ ],
          "search_string" : "archaea",
          "score" : 1.0,
          "synonyms" : [ "Archäa", "Archaea" ],
          "is_approximate_match" : false,
          "ot:ottId" : 5264182,
          "matched_node_id" : 1056380,
          "rank" : "",
          "matched_name" : "Archaea",
          "unique_name" : "Archaea (genus in family Archaeidae)",
          "is_dubious" : false,
          "nomenclature_code" : "ICZN",
          "ot:ottTaxonName" : "Archaea"
        }, {
          "is_deprecated" : false,
          "is_synonym" : true,
          "flags" : [ ],
          "search_string" : "archaea",
          "score" : 1.0,
          "synonyms" : [ "Archaea", "archaea", "Archaebacteria", "Mendosicutes", "Metabacteria" ],
          "is_approximate_match" : false,
          "ot:ottId" : 996421,
          "matched_node_id" : 478643,
          "rank" : "",
          "matched_name" : "archaea",
          "unique_name" : "Archaea (domain in cellular organisms)",
          "is_dubious" : false,
          "nomenclature_code" : null,
          "ot:ottTaxonName" : "Archaea"
        } ]
      } ]
    }

**Comment by josephwb** [comment]
Seems like it is just returning the name and the synonym, right?

**Comment by mtholder** [comment]
yeah. you're right. I did not notice the case difference as a synonym. sorry.
